name: flutter_ml
description: A deep learning framework in pure Dart with a dynamic autograd engine. Designed for education, research, and understanding the core mechanics of AI.
version: 2.0.0
homepage: https://github.com/NoirsCodingCorner/flutter_ml
repository: https://github.com/NoirsCodingCorner/flutter_ml
license: Apache-2.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
# This package currently has no platform-specific assets or fonts.